//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hztoolbar {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("hztoolbar.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To bottom guide.
        /// </summary>
        public static string align_guide_bottom_label {
            get {
                return ResourceManager.GetString("align_guide_bottom_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To left guide.
        /// </summary>
        public static string align_guide_left_label {
            get {
                return ResourceManager.GetString("align_guide_left_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To right guide.
        /// </summary>
        public static string align_guide_right_label {
            get {
                return ResourceManager.GetString("align_guide_right_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To top guide.
        /// </summary>
        public static string align_guide_top_label {
            get {
                return ResourceManager.GetString("align_guide_top_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent 1.
        /// </summary>
        public static string apply_background_accent1_theme_color_label {
            get {
                return ResourceManager.GetString("apply_background_accent1_theme_color_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent 2.
        /// </summary>
        public static string apply_background_accent2_theme_color_label {
            get {
                return ResourceManager.GetString("apply_background_accent2_theme_color_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent 3.
        /// </summary>
        public static string apply_background_accent3_theme_color_label {
            get {
                return ResourceManager.GetString("apply_background_accent3_theme_color_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent 4.
        /// </summary>
        public static string apply_background_accent4_theme_color_label {
            get {
                return ResourceManager.GetString("apply_background_accent4_theme_color_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent 5.
        /// </summary>
        public static string apply_background_accent5_theme_color_label {
            get {
                return ResourceManager.GetString("apply_background_accent5_theme_color_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent 6.
        /// </summary>
        public static string apply_background_accent6_theme_color_label {
            get {
                return ResourceManager.GetString("apply_background_accent6_theme_color_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark 1.
        /// </summary>
        public static string apply_background_dark1_theme_color_label {
            get {
                return ResourceManager.GetString("apply_background_dark1_theme_color_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark 2.
        /// </summary>
        public static string apply_background_dark2_theme_color_label {
            get {
                return ResourceManager.GetString("apply_background_dark2_theme_color_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light 1.
        /// </summary>
        public static string apply_background_light1_theme_color_label {
            get {
                return ResourceManager.GetString("apply_background_light1_theme_color_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light 2.
        /// </summary>
        public static string apply_background_light2_theme_color_label {
            get {
                return ResourceManager.GetString("apply_background_light2_theme_color_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent 1.
        /// </summary>
        public static string apply_line_accent1_theme_color_label {
            get {
                return ResourceManager.GetString("apply_line_accent1_theme_color_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent 2.
        /// </summary>
        public static string apply_line_accent2_theme_color_label {
            get {
                return ResourceManager.GetString("apply_line_accent2_theme_color_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent 3.
        /// </summary>
        public static string apply_line_accent3_theme_color_label {
            get {
                return ResourceManager.GetString("apply_line_accent3_theme_color_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent 4.
        /// </summary>
        public static string apply_line_accent4_theme_color_label {
            get {
                return ResourceManager.GetString("apply_line_accent4_theme_color_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent 5.
        /// </summary>
        public static string apply_line_accent5_theme_color_label {
            get {
                return ResourceManager.GetString("apply_line_accent5_theme_color_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent 6.
        /// </summary>
        public static string apply_line_accent6_theme_color_label {
            get {
                return ResourceManager.GetString("apply_line_accent6_theme_color_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark 1.
        /// </summary>
        public static string apply_line_dark1_theme_color_label {
            get {
                return ResourceManager.GetString("apply_line_dark1_theme_color_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark 2.
        /// </summary>
        public static string apply_line_dark2_theme_color_label {
            get {
                return ResourceManager.GetString("apply_line_dark2_theme_color_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light 1.
        /// </summary>
        public static string apply_line_light1_theme_color_label {
            get {
                return ResourceManager.GetString("apply_line_light1_theme_color_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light 2.
        /// </summary>
        public static string apply_line_light2_theme_color_label {
            get {
                return ResourceManager.GetString("apply_line_light2_theme_color_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrange shapes.
        /// </summary>
        public static string arrange_actions_label {
            get {
                return ResourceManager.GetString("arrange_actions_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive gutters.
        /// </summary>
        public static string arrange_grid_control_label {
            get {
                return ResourceManager.GetString("arrange_grid_control_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Grid.
        /// </summary>
        public static string arrange_grid_label {
            get {
                return ResourceManager.GetString("arrange_grid_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large gutters.
        /// </summary>
        public static string arrange_grid_large_label {
            get {
                return ResourceManager.GetString("arrange_grid_large_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal gutters.
        /// </summary>
        public static string arrange_grid_medium_label {
            get {
                return ResourceManager.GetString("arrange_grid_medium_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No gutters.
        /// </summary>
        public static string arrange_grid_none_label {
            get {
                return ResourceManager.GetString("arrange_grid_none_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small gutters.
        /// </summary>
        public static string arrange_grid_small_label {
            get {
                return ResourceManager.GetString("arrange_grid_small_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        public static string arrange_horizontal_label {
            get {
                return ResourceManager.GetString("arrange_horizontal_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnet.
        /// </summary>
        public static string arrange_magnet_label {
            get {
                return ResourceManager.GetString("arrange_magnet_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string arrange_shape_settings_dialog_cancel_label {
            get {
                return ResourceManager.GetString("arrange_shape_settings_dialog_cancel_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string arrange_shape_settings_dialog_close_label {
            get {
                return ResourceManager.GetString("arrange_shape_settings_dialog_close_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gutter.
        /// </summary>
        public static string arrange_shape_settings_dialog_gutter_label {
            get {
                return ResourceManager.GetString("arrange_shape_settings_dialog_gutter_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal gutter.
        /// </summary>
        public static string arrange_shape_settings_dialog_horizontal_gutter_label {
            get {
                return ResourceManager.GetString("arrange_shape_settings_dialog_horizontal_gutter_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        public static string arrange_shape_settings_dialog_horizontal_label {
            get {
                return ResourceManager.GetString("arrange_shape_settings_dialog_horizontal_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string arrange_shape_settings_dialog_ok_label {
            get {
                return ResourceManager.GetString("arrange_shape_settings_dialog_ok_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize.
        /// </summary>
        public static string arrange_shape_settings_dialog_resize_label {
            get {
                return ResourceManager.GetString("arrange_shape_settings_dialog_resize_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close &amp; Save.
        /// </summary>
        public static string arrange_shape_settings_dialog_save_label {
            get {
                return ResourceManager.GetString("arrange_shape_settings_dialog_save_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrange shapes.
        /// </summary>
        public static string arrange_shape_settings_dialog_title {
            get {
                return ResourceManager.GetString("arrange_shape_settings_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical gutter.
        /// </summary>
        public static string arrange_shape_settings_dialog_vertical_gutter_label {
            get {
                return ResourceManager.GetString("arrange_shape_settings_dialog_vertical_gutter_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        public static string arrange_shape_settings_dialog_vertical_label {
            get {
                return ResourceManager.GetString("arrange_shape_settings_dialog_vertical_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        public static string arrange_vertical_label {
            get {
                return ResourceManager.GetString("arrange_vertical_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change to German.
        /// </summary>
        public static string change_language_de {
            get {
                return ResourceManager.GetString("change_language_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change to English.
        /// </summary>
        public static string change_language_en {
            get {
                return ResourceManager.GetString("change_language_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear text.
        /// </summary>
        public static string clear_text_label {
            get {
                return ResourceManager.GetString("clear_text_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme color.
        /// </summary>
        public static string color_actions_label {
            get {
                return ResourceManager.GetString("color_actions_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy shape.
        /// </summary>
        public static string copy_shape_label {
            get {
                return ResourceManager.GetString("copy_shape_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy type.
        /// </summary>
        public static string copy_shape_type_label {
            get {
                return ResourceManager.GetString("copy_shape_type_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidelines.
        /// </summary>
        public static string guideline_actions_label {
            get {
                return ResourceManager.GetString("guideline_actions_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Adjustments.
        /// </summary>
        public static string harmonize_adjustments_label {
            get {
                return ResourceManager.GetString("harmonize_adjustments_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Height.
        /// </summary>
        public static string harmonize_shape_height_label {
            get {
                return ResourceManager.GetString("harmonize_shape_height_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Size.
        /// </summary>
        public static string harmonize_shape_size_label {
            get {
                return ResourceManager.GetString("harmonize_shape_size_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Width.
        /// </summary>
        public static string harmonize_shape_width_label {
            get {
                return ResourceManager.GetString("harmonize_shape_width_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal distribute between guides.
        /// </summary>
        public static string horizontal_resize_distribute_guide_label {
            get {
                return ResourceManager.GetString("horizontal_resize_distribute_guide_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal fit to guides.
        /// </summary>
        public static string horizontal_resize_guide_label {
            get {
                return ResourceManager.GetString("horizontal_resize_guide_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge texts.
        /// </summary>
        public static string merge_text_label {
            get {
                return ResourceManager.GetString("merge_text_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Shape.
        /// </summary>
        public static string repeat_last_shape_change_label {
            get {
                return ResourceManager.GetString("repeat_last_shape_change_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape.
        /// </summary>
        public static string shape_actions_label {
            get {
                return ResourceManager.GetString("shape_actions_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string split_rectangle_dialog_cancel_label {
            get {
                return ResourceManager.GetString("split_rectangle_dialog_cancel_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cells.
        /// </summary>
        public static string split_rectangle_dialog_cells_label {
            get {
                return ResourceManager.GetString("split_rectangle_dialog_cells_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string split_rectangle_dialog_columns_label {
            get {
                return ResourceManager.GetString("split_rectangle_dialog_columns_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gutter Size.
        /// </summary>
        public static string split_rectangle_dialog_gutter_label {
            get {
                return ResourceManager.GetString("split_rectangle_dialog_gutter_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string split_rectangle_dialog_ok_label {
            get {
                return ResourceManager.GetString("split_rectangle_dialog_ok_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        public static string split_rectangle_dialog_rows_label {
            get {
                return ResourceManager.GetString("split_rectangle_dialog_rows_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split.
        /// </summary>
        public static string split_rectangle_dialog_title {
            get {
                return ResourceManager.GetString("split_rectangle_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split rectangle.
        /// </summary>
        public static string split_rectangle_label {
            get {
                return ResourceManager.GetString("split_rectangle_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Text.
        /// </summary>
        public static string split_text_label {
            get {
                return ResourceManager.GetString("split_text_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap text.
        /// </summary>
        public static string swap_text_label {
            get {
                return ResourceManager.GetString("swap_text_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string text_actions_label {
            get {
                return ResourceManager.GetString("text_actions_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom margins.
        /// </summary>
        public static string text_margin_custom_label {
            get {
                return ResourceManager.GetString("text_margin_custom_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset margins.
        /// </summary>
        public static string text_margin_default_label {
            get {
                return ResourceManager.GetString("text_margin_default_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large margins.
        /// </summary>
        public static string text_margin_large_label {
            get {
                return ResourceManager.GetString("text_margin_large_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No margins.
        /// </summary>
        public static string text_margin_none_label {
            get {
                return ResourceManager.GetString("text_margin_none_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal margins.
        /// </summary>
        public static string text_margin_normal_label {
            get {
                return ResourceManager.GetString("text_margin_normal_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small margins.
        /// </summary>
        public static string text_margin_small_label {
            get {
                return ResourceManager.GetString("text_margin_small_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical distribute between guides.
        /// </summary>
        public static string vertical_resize_distribute_guide_label {
            get {
                return ResourceManager.GetString("vertical_resize_distribute_guide_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical fit to guides.
        /// </summary>
        public static string vertical_resize_guide_label {
            get {
                return ResourceManager.GetString("vertical_resize_guide_label", resourceCulture);
            }
        }
    }
}
